### ISSUE TITLE
Provide native json serializability for custom class Objects such as Actor, Rule, etc.

### ISSUE THREAD

**Issue by RonGonz-illumio** [illumio/illumio-py#29]
Currently trying to serialize rule objects using json.dumps will return a _TypeError: Object of type 'X' is not JSON serializable_ exception.

This ER is requesting that native serialization support for custom objects be built into the different class types so that it's easy to dump them to json for reporting purposes, especially since they already resemble (or are essentially) dict objects.

## Use case  
Want to compile a dictionary of rulesets (name key) with the value for each key being a list of rules.

## Example  

```
{'APP_A': [Rule(href='/orgs/1/sec_policy/draft/rule_sets/4113/sec_rules/8308', name=None, description='', external_data_set=None, external_data_reference=None, caps=None, created_at='2023-01-12T01:05:05.798Z', updated_at='2023-01-12T01:05:05.824Z', deleted_at=None, update_type=None, delete_type=None, created_by=Reference(href='/users/1'), updated_by=Reference(href='/users/1'), deleted_by=None, ingress_services=[Service(href='/orgs/1/sec_policy/draft/services/1', name=None, description=None, external_data_set=None, external_data_reference=None, caps=None, created_at=None, updated_at=None, deleted_at=None, update_type=None, delete_type=None, created_by=None, updated_by=None, deleted_by=None, process_name=None, service_ports=None, windows_services=None, windows_egress_services=None)], providers=[Actor(actors='ams', label=None, label_group=None, workload=None, virtual_service=None, virtual_server=None, ip_list=None)], consumers=[Actor(actors=None, label=None, label_group=None, workload=Reference(href='/orgs/1/workloads/c56ce3b1-3bdd-452b-b1de-1c29a9db66fd'), virtual_service=None, virtual_server=None, ip_list=None)], enabled=True, resolve_labels_as=LabelResolutionBlock(providers=['workloads'], consumers=['workloads']), sec_connect=False, stateless=False, machine_auth=False, consuming_security_principals=[], unscoped_consumers=False, network_type='brn')]}


  with open(file_name, 'w') as outfile:
      json.dump(self._rulesets_with_workload_rules, outfile)

```
results in:

```
Traceback (most recent call last):
  File "XXX.py", line 763, in inspect_pce_rule_sets
    json.dump(self._rulesets_with_workload_rules, outfile)
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Rule is not JSON serializable
```

**Comment by dsommerville-illumio** [comment]
Python doesn't have a simple way of tacking serialization/deserialization onto a class, which is why `JsonObject` implements `to_json()`/`from_json()`. If you need to use `json.load`/`json.dump`, there's a convenience class `illumio.util.jsonutils.IllumioEncoder` that you can use:

```
from illumio.util import IllumioEncoder

out = {'APP_A': [Rule(...)]}
print(json.dumps(out, cls=IllumioEncoder))
```

**Comment by RonGonz-illumio** [comment]
Very nice!

I built my own custom encoder before I saw this message!
In any event, I like your encoder better, it returns all the object fields correctly.

> Python doesn't have a simple way of tacking JSON serialization/deserialization onto a class,

You could inherit from dict in the requisite classes, then add a dict.__init__ call from __init__ that just returns the output of the illumio encoder, I haven't tried that yet, but it might work and make the classes serializable with the standard json dump library.

**Comment by RonGonz-illumio** [comment]
feel free to close, the illumio encoder works!
