### ISSUE TITLE
pce.label_groups.get() throws AttributeError if label_group has non-empty sub_groups list

### ISSUE THREAD

**Issue by y-myk** [illumio/illumio-py#40]
Running pce.label_groups.get() matching a lable_group with non-empty sub_groups list throws AttributeError error:

`Traceback (most recent call last):
  File "/Users/ymyk/git/workspaces/python/illumio_rules_dumper/illumio_rules_dumper.py", line 217, in <module>
    get_label_groups()
  File "/Users/ymyk/git/workspaces/python/illumio_rules_dumper/illumio_rules_dumper.py", line 184, in get_label_groups
    label_groups = pce.label_groups.get(
  File "/Users/ymyk/Documents/projects/IllNet/.illumio_rules_dumper/lib/python3.10/site-packages/illumio/pce.py", line 500, in get
    return [self.object_cls.from_json(o) for o in response.json()]
  File "/Users/ymyk/Documents/projects/IllNet/.illumio_rules_dumper/lib/python3.10/site-packages/illumio/pce.py", line 500, in <listcomp>
    return [self.object_cls.from_json(o) for o in response.json()]
  File "/Users/ymyk/Documents/projects/IllNet/.illumio_rules_dumper/lib/python3.10/site-packages/illumio/util/jsonutils.py", line 130, in from_json
    o = cls(**defined_params)
  File "<string>", line 23, in __init__
  File "/Users/ymyk/Documents/projects/IllNet/.illumio_rules_dumper/lib/python3.10/site-packages/illumio/util/jsonutils.py", line 47, in __post_init__
    self._validate()
  File "/Users/ymyk/Documents/projects/IllNet/.illumio_rules_dumper/lib/python3.10/site-packages/illumio/util/jsonutils.py", line 54, in _validate
    raise AttributeError("Invalid value for {}: {}. Must be of type {}".format(field.name, value, field.type))
AttributeError: Invalid value for sub_groups: [{'href': '/orgs/1/sec_policy/active/label_groups/1665befc-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'name': 'Every AP Location'}]. Must be of type typing.List[ForwardRef('LabelGroup')]    `

Label_group details: 

```
  {
    "href": "/orgs/1/sec_policy/active/label_groups/38059c02-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "created_at": "2019-12-16T08:34:20.016Z",
    "updated_at": "2019-12-16T08:34:30.983Z",
    "deleted_at": null,
    "created_by": {
      "href": "/users/xxx"
    },
    "updated_by": {
      "href": "/users/xxx"
    },
    "deleted_by": null,
    "name": "Every AP Location",
    "description": "Every Asia-Pacific location",
    "key": "loc",
    "labels": [],
    "sub_groups": [
      {
        "href": "/orgs/1/sec_policy/active/label_groups/1665befc-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "name": "Every AP Location"
      }
    ]
  },
```
  
## Expected Result

I would expect the function to return label_group object(s)

## Actual Result

AttributeError exception

## Steps to reproduce

```
from illumio import PolicyComputeEngine

pce = PolicyComputeEngine('pce-fqdn', port=8443, org_id=1)
pce.set_credentials(os.environ.get('ILLUMIO_API_USERNAME'), os.environ.get('ILLUMIO_API_SECRET'))

def get_label_groups(policy_version='active'):
    # Get label_groups
    label_groups = pce.label_groups.get(
        policy_version=policy_version,
        params={
            'name': "Every AP Location",
        }
    )

    return label_groups
    
if __name__ == '__main__':
    get_label_groups()
```

## System Information

```
$ pip freeze
certifi==2023.7.22
charset-normalizer==3.2.0
idna==3.4
illumio==1.1.3
requests==2.31.0
urllib3==2.0.4
```

**Are you able to help contribute a fix for this issue?** yes/no

no

**Comment by RonGonz-illumio** [comment]
dupe of #36

**Comment by y-myk** [comment]
Thank you. Modified [label.py#95](https://github.com/illumio/illumio-py/blob/0d781c555b245da384ce18dac1d7063b951ce8b3/illumio/policyobjects/label.py#L95) as a workaround.

Is the fix going to be added in the next release?
